
# Configuration for Documasonry

default_templates:

  - file: 'E:\GitHub\Documasonry\test\test_templates\_test_{{项目名称}}-申请表.xls'
    selected: false
    required_fields: ['field1', 'field2', 'field3']

  - file: 'test\test_templates\test_{{name}}_面积计算表.doc'
    selected: false

  - file: 'E:\GitHub\Documasonry\test\test_templates\test_{{测试单位}}-宗地图.dwg'
    selected: false
    required_fields: ['field1', 'field2', 'field4']








default_output_path: 'E:\GitHub\Documasonry'
